languageCode = "en-us"
title = "Barriers"
baseURL = "/"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "A description about Belize"
    meta_og_title = "Barriers"
    meta_og_type = "website"
    meta_og_url = ""
    meta_og_image = ""
    meta_og_description = ""
    meta_twitter_card = "A description about Belize"
    meta_twitter_site = ""
    meta_twitter_creator = ""

[[menu.main]]
	name = "Stories"
	url = "/stories/"
    weight = 1

[[menu.main]]
    name = "Photo Journey"
    url = "/photo/"
    weight = 2

[[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 3

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
