languageCode = "en-us"
title = "Barriers"
baseURL = "/"
enableInlineShortcodes = "true"
canonifyURLs = "true"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "A description about Belize"
    meta_og_title = "Barriers"
    meta_og_type = "website"
    meta_og_url = ""
    meta_og_image = ""
    meta_og_description = ""
    meta_twitter_card = "A description about Belize"
    meta_twitter_site = ""
    meta_twitter_creator = ""

[[menu.main]]
	name = "Threatened Water"
	url = "/story01/"
    weight = 1

[[menu.main]]
    name = "Monkey River"
    url = "/story02/"
    weight = 2

[[menu.main]]
    name = "The Cost of Chocolate"
    url = "/story03/"
    weight = 3

[[menu.main]]
    name = "Tied By Trash"
    url = "/story04/"
    weight = 4

[[menu.main]]
    name = "Seaweed for All"
    url = "/story05/"
    weight = 5

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 6

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"

  [markup]
    [markup.goldmark]
      [markup.goldmark.extensions]
        definitionList = true
        footnote = true
        linkify = true
        strikethrough = true
        table = true
        taskList = true
        typographer = true
      [markup.goldmark.parser]
        attribute = true
        autoHeadingID = true
        autoHeadingIDType = "github"
      [markup.goldmark.renderer]
        hardWraps = true
        unsafe = true
        xHTML = true
