languageCode = "en-us"
title = "Barriers"
baseURL = "/"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "A description about Belize"
    meta_og_title = "Barriers"
    meta_og_type = "website"
    meta_og_url = ""
    meta_og_image = ""
    meta_og_description = ""
    meta_twitter_card = "A description about Belize"
    meta_twitter_site = ""
    meta_twitter_creator = ""

[[menu.main]]
	name = "Story 1"
	url = "/story01/"
    weight = 1

[[menu.main]]
    name = "Story 2"
    url = "/story02/"
    weight = 2

[[menu.main]]
    name = "Story 3"
    url = "/story03/"
    weight = 3

[[menu.main]]
    name = "Story 4"
    url = "/story04/"
    weight = 4

[[menu.main]]
    name = "Story 5"
    url = "/story05/"
    weight = 5

[[menu.main]]
    name = "About Us"
    url = "/about/"
    weight = 6

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
